-- Panel Sales Tracker — initial Postgres schema (migrated from SQLite).
-- Booleans are real booleans, timestamps are timestamptz, scoring_config.options
-- is jsonb. PKs use GENERATED BY DEFAULT so original ids could be inserted
-- during the data migration, then sequences were reset.

-- ===== Deals pipeline =====
create table public.deals (
  id                 bigint generated by default as identity primary key,
  brand_name         text not null,
  vertical           text,
  owner              text,
  source             text,
  current_stage      text not null,
  channel            text,
  fast_track         boolean not null default false,
  pilot_spend        integer,
  intent_notes       text,
  closed_lost_reason text,
  created_at         timestamptz not null,
  updated_at         timestamptz not null
);

create table public.stage_history (
  id         bigint generated by default as identity primary key,
  deal_id    bigint not null references public.deals(id) on delete cascade,
  stage      text not null,
  entered_at timestamptz not null
);
create index idx_stage_history_deal on public.stage_history(deal_id);

create table public.touch_log (
  id         bigint generated by default as identity primary key,
  deal_id    bigint not null references public.deals(id) on delete cascade,
  touch_date timestamptz not null,
  touch_type text,
  outcome    text,
  notes      text,
  created_at timestamptz not null
);
create index idx_touch_log_deal on public.touch_log(deal_id);

-- ===== Lead intelligence =====
create table public.verticals (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null
);

create table public.leads (
  id               bigint generated by default as identity primary key,
  company_name     text not null,
  vertical_id      bigint references public.verticals(id) on delete set null,
  website          text,
  score            integer not null default 0,
  score_updated_at timestamptz,
  in_pipeline      boolean not null default false,
  deal_id          bigint,
  created_at       timestamptz not null,
  updated_at       timestamptz not null
);
create index idx_leads_vertical on public.leads(vertical_id);

create table public.lead_signals (
  id         bigint generated by default as identity primary key,
  lead_id    bigint not null references public.leads(id) on delete cascade,
  signal_key text not null,
  value      text,
  notes      text,
  updated_at timestamptz not null,
  unique (lead_id, signal_key)
);
create index idx_lead_signals_lead on public.lead_signals(lead_id);

create table public.lead_contacts (
  id         bigint generated by default as identity primary key,
  lead_id    bigint not null references public.leads(id) on delete cascade,
  name       text,
  title      text,
  linkedin   text,
  created_at timestamptz not null
);
create index idx_lead_contacts_lead on public.lead_contacts(lead_id);

create table public.scoring_config (
  id         bigint generated by default as identity primary key,
  signal_key text not null unique,
  label      text not null,
  category   text not null,
  input_type text not null,
  options    jsonb,
  max_points integer not null default 0,
  sort_order integer not null default 0,
  updated_at timestamptz not null
);
