-- Per-user Workspace Gmail + Calendar integration.
--
-- This is the first per-user-private data in the schema. Until now every table
-- used the blanket "authenticated full access" policy (a shared workspace).
-- Google tokens must NOT be shared, so the connection / suggestion / meeting /
-- domain-rule tables get auth.uid()-scoped policies instead. The shared CRM
-- tables (deal_email_links + new touch_log columns) keep the workspace model.
--
-- Refresh/access tokens are encrypted at the application layer (AES-GCM) inside
-- the Edge Functions using a key held as a Supabase function secret — the DB
-- only ever stores ciphertext, and the client never reads the token columns
-- (it reads status through the gmail_connection_status view below).

-- ===== Per-user Google connection (tokens encrypted; service-role writes) =====
create table public.gmail_connections (
  user_id             uuid primary key references auth.users(id) on delete cascade,
  google_email        text not null,
  scopes              text[] not null default '{}',
  refresh_token_enc   text not null,                 -- AES-GCM ciphertext; never sent to client
  access_token_enc    text,                          -- short-lived cache, optional
  access_token_exp    timestamptz,
  history_id          text,                          -- Gmail History API cursor
  calendar_sync_token text,                          -- Calendar incremental sync cursor
  watch_expiration    timestamptz,                   -- for an optional future push/watch model
  auto_advance_s1_s2  boolean not null default false,-- per-rep opt-in: reply auto-moves S1 -> S2
  status              text not null default 'active',-- active | needs_reauth | revoked
  last_synced_at      timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

alter table public.gmail_connections enable row level security;

-- A rep may READ only their own connection row. All writes (insert/update) come
-- from Edge Functions using the service-role key, which bypasses RLS — so no
-- write policy is granted to authenticated, by design.
create policy "own connection read" on public.gmail_connections
  for select to authenticated using (user_id = auth.uid());

-- Client-safe status view: exposes everything EXCEPT the token columns. Used by
-- the Integrations screen. security_invoker so the caller's RLS applies.
create view public.gmail_connection_status with (security_invoker = true) as
select
  user_id,
  google_email,
  scopes,
  auto_advance_s1_s2,
  status,
  last_synced_at,
  created_at,
  updated_at
from public.gmail_connections;

-- ===== Deal <-> email thread / contact mapping (shared workspace data) =====
create table public.deal_email_links (
  id             bigint generated by default as identity primary key,
  deal_id        bigint not null references public.deals(id) on delete cascade,
  thread_id      text,                  -- Gmail threadId
  contact_email  text,                  -- normalized lowercase
  contact_domain text,
  created_by     uuid references auth.users(id) on delete set null,
  created_at     timestamptz not null default now(),
  unique (deal_id, thread_id)
);
create index idx_deal_email_links_thread on public.deal_email_links(thread_id);
create index idx_deal_email_links_email  on public.deal_email_links(contact_email);
create index idx_deal_email_links_domain on public.deal_email_links(contact_domain);

-- ===== Review queue: outbound-to-new-external + ambiguous matches (per-user) =====
create table public.email_suggestions (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users(id) on delete cascade,
  thread_id        text not null,
  contact_email    text,
  contact_domain   text,
  subject          text,
  direction        text not null,        -- outbound | inbound
  proposed_action  text not null,        -- create_deal | attach_deal | stage_move
  proposed_deal_id bigint references public.deals(id) on delete set null,
  proposed_stage   text,
  status           text not null default 'pending',  -- pending | accepted | dismissed
  first_seen_at    timestamptz not null default now(),
  resolved_at      timestamptz,
  unique (user_id, thread_id, proposed_action)
);
create index idx_email_suggestions_user_status
  on public.email_suggestions(user_id, status);

alter table public.email_suggestions enable row level security;
-- A rep sees and resolves only their own suggestions. Edge Functions create
-- them via the service-role key.
create policy "own suggestions all" on public.email_suggestions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ===== Domain rules for noise control (per-rep or workspace-wide) =====
create table public.email_domain_rules (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users(id) on delete cascade,  -- null = workspace-wide
  domain     text not null,
  rule       text not null,            -- ignore | auto_suggest
  created_at timestamptz not null default now(),
  unique (user_id, domain)
);
create index idx_email_domain_rules_domain on public.email_domain_rules(domain);

alter table public.email_domain_rules enable row level security;
-- A rep manages their own rules and may read the workspace-wide ones
-- (user_id is null). They can only write rows scoped to themselves.
create policy "domain rules read" on public.email_domain_rules
  for select to authenticated
  using (user_id = auth.uid() or user_id is null);
create policy "domain rules write own" on public.email_domain_rules
  for insert to authenticated with check (user_id = auth.uid());
create policy "domain rules update own" on public.email_domain_rules
  for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "domain rules delete own" on public.email_domain_rules
  for delete to authenticated using (user_id = auth.uid());

-- ===== Calendar meetings surfaced onto deals (per-user) =====
create table public.meetings (
  id              bigint generated by default as identity primary key,
  deal_id         bigint references public.deals(id) on delete cascade,
  user_id         uuid not null references auth.users(id) on delete cascade,
  google_event_id text not null,
  title           text,
  starts_at       timestamptz,
  ends_at         timestamptz,
  attendees       jsonb,
  status          text,
  created_at      timestamptz not null default now(),
  unique (user_id, google_event_id)
);
create index idx_meetings_deal on public.meetings(deal_id);

alter table public.meetings enable row level security;
-- Meetings are tied to a rep's calendar; they read their own. Edge Functions
-- upsert via service-role. (Deal panel shows meetings the connected rep synced.)
create policy "own meetings read" on public.meetings
  for select to authenticated using (user_id = auth.uid());

-- ===== Extend touch_log so Gmail-sourced touches are deduped + distinguishable =====
-- Inherits the existing workspace-wide RLS from 0002 (shared CRM timeline).
alter table public.touch_log add column if not exists source      text;  -- 'manual' | 'gmail'
alter table public.touch_log add column if not exists external_id text;  -- Gmail Message-ID, for dedupe
-- One touch per Gmail message: re-polling the same message must not duplicate.
create unique index if not exists uq_touch_external
  on public.touch_log(external_id) where external_id is not null;
