-- v2 — Person profiles + per-person outreach history.
-- People (lead_contacts) become first-class profiles, and outreach is now
-- tracked at the person level (not just per-deal in touch_log).

-- Person profile fields (filled in during prospecting).
alter table public.lead_contacts add column if not exists phone     text;
alter table public.lead_contacts add column if not exists location  text;
alter table public.lead_contacts add column if not exists seniority text;  -- role level / dept
alter table public.lead_contacts add column if not exists notes     text;

-- Per-person outreach log — mirrors touch_log but keyed to a contact, with an
-- owner. A person may have touches before any deal exists.
create table if not exists public.contact_touches (
  id         bigint generated by default as identity primary key,
  contact_id bigint not null references public.lead_contacts(id) on delete cascade,
  touch_date timestamptz not null,
  touch_type text,
  outcome    text,
  owner      text,
  notes      text,
  created_at timestamptz not null
);
create index if not exists idx_contact_touches_contact on public.contact_touches(contact_id);

-- Same allowlist-only RLS as every other table (see 0002).
alter table public.contact_touches enable row level security;
create policy "authenticated full access" on public.contact_touches
  for all to authenticated using (true) with check (true);
