-- Phase 4: turn scanned mail into PEOPLE + COMPANIES (not just deals).
--
-- The existing email_suggestions queue proposes *deals*. This migration adds a
-- parallel, company-grouped queue: a rep scans their connected inbox, we extract
-- the external person + their company from each sent email, de-dupe against the
-- CRM, and file pending suggestions the rep approves/rejects from the Review
-- Queue. Approving creates the company (leads) + its people (lead_contacts), or
-- — when the company already exists — just attaches the new people to it.
--
-- Same trust model as 0006: per-user rows are auth.uid()-scoped (a rep only sees
-- their own scan results); Edge Functions write via the service-role key.

-- ===== Proposed / matched company (one row per user+domain) =====
create table public.company_suggestions (
  id                    bigint generated by default as identity primary key,
  user_id               uuid not null references auth.users(id) on delete cascade,
  proposed_company_name text,
  domain                text not null,                       -- normalized registrable domain
  matched_lead_id       bigint references public.leads(id) on delete set null, -- null = propose new company
  confidence            text,                                -- high | medium | low (from extractor)
  status                text not null default 'pending',     -- pending | accepted | dismissed
  first_seen_at         timestamptz not null default now(),
  resolved_at           timestamptz,
  -- Re-scanning the same domain updates one row instead of piling up duplicates.
  unique (user_id, domain)
);
create index idx_company_suggestions_user_status
  on public.company_suggestions(user_id, status);

alter table public.company_suggestions enable row level security;
create policy "own company suggestions all" on public.company_suggestions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ===== Proposed / matched person (child of a company suggestion) =====
create table public.contact_suggestions (
  id                    bigint generated by default as identity primary key,
  user_id               uuid not null references auth.users(id) on delete cascade,
  company_suggestion_id bigint not null references public.company_suggestions(id) on delete cascade,
  matched_contact_id    bigint references public.lead_contacts(id) on delete set null, -- set = already in CRM
  name                  text,
  email                 text,                                -- normalized lowercase
  title                 text,
  phone                 text,
  linkedin              text,
  location              text,
  seniority             text,
  source_thread_id      text,
  source_message_id     text,
  subject               text,
  two_way               boolean not null default false,      -- prospect replied on the thread
  status                text not null default 'pending',     -- pending | accepted | dismissed
  first_seen_at         timestamptz not null default now(),
  resolved_at           timestamptz,
  -- The same person is never queued twice across scans (per rep).
  unique (user_id, email)
);
create index idx_contact_suggestions_company
  on public.contact_suggestions(company_suggestion_id);
create index idx_contact_suggestions_user_status
  on public.contact_suggestions(user_id, status);

alter table public.contact_suggestions enable row level security;
create policy "own contact suggestions all" on public.contact_suggestions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ===== Backfill job (drives the long-running inbox scan, one row per rep) =====
-- The scan walks the whole sent mailbox in batches; a single Edge Function
-- invocation can't outrun its time limit, so we persist a cursor (page_token)
-- and re-drive the function until status flips to 'done'.
create table public.gmail_scan_jobs (
  user_id         uuid primary key references auth.users(id) on delete cascade,
  status          text not null default 'queued',  -- queued | running | done | error
  page_token      text,                            -- Gmail messages.list cursor
  processed_count integer not null default 0,
  suggested_count integer not null default 0,
  error           text,
  started_at      timestamptz,
  updated_at      timestamptz not null default now()
);

alter table public.gmail_scan_jobs enable row level security;
-- A rep reads only their own job (for the progress UI). Edge Functions write
-- via the service-role key, so no write policy is granted to authenticated.
create policy "own scan job read" on public.gmail_scan_jobs
  for select to authenticated using (user_id = auth.uid());

-- ===== Dedup support on the CRM tables =====
-- A normalized domain column on leads makes company matching an exact indexed
-- lookup (instead of fuzzy-matching the free-text website). Backfilled from the
-- existing website values; new companies populate it on insert (see api.js +
-- accept_company_suggestion).
alter table public.leads add column if not exists domain text;
create index if not exists idx_leads_domain on public.leads(domain);

update public.leads
   set domain = nullif(
         split_part(
           regexp_replace(
             regexp_replace(lower(btrim(website)), '^https?://', '', 'i'),
             '^www\.', '', 'i'
           ),
           '/', 1
         ),
         ''
       )
 where website is not null and btrim(website) <> '' and domain is null;

-- Person-by-email matching is case-insensitive.
create index if not exists idx_lead_contacts_email_lower
  on public.lead_contacts(lower(email));
