-- Activation Surface — replaces the A1–A5 Kanban with a per-brand 30-day clock to
-- first conversion. A brand has lanes (workstreams), lanes have tasks (two levels),
-- and any item can depend on any other in one flat dependency graph. Lanes and tasks
-- share a single table (activation_items) so ids are globally unique and the
-- dependency graph (activation_deps) is a plain self-referential edge set.
--
-- All computation (effective status, blocked, roll-up, deadline risk, brand health)
-- is done client-side in lib/activation.js — only raw rows live here.

-- ===== Tables =====

-- One row per won brand on the surface. deal_id is the link back to the pipeline;
-- committed_date anchors the 30-day clock; activated_date is stamped when the Live
-- lane completes.
create table public.activation_brands (
  id            bigint generated by default as identity primary key,
  deal_id       bigint not null unique references public.deals(id) on delete cascade,
  committed_date date not null,
  activated_date date,
  runway_days   integer not null default 30,
  goal_day      integer not null default 30,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index idx_activation_brands_deal on public.activation_brands(deal_id);

-- Lanes AND tasks. kind='lane' rows have parent_item_id null; kind='task' rows point
-- at their lane. status is authoritative for tasks and for custom (task-less) lanes;
-- system lanes roll up from their child tasks. override (lanes only in the UI) wins
-- outright when set. hard_deadline_day is the template offset from committed_date;
-- an explicit due date overrides it.
create table public.activation_items (
  id              bigint generated by default as identity primary key,
  brand_id        bigint not null references public.activation_brands(id) on delete cascade,
  kind            text not null check (kind in ('lane','task')),
  parent_item_id  bigint references public.activation_items(id) on delete cascade,
  label           text not null,
  status          text not null default 'not_started',
  override        text,
  is_system       boolean not null default false,
  is_live         boolean not null default false,
  hard_deadline_day integer,
  due             date,
  owner           text,
  sort_order      integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index idx_activation_items_brand on public.activation_items(brand_id);
create index idx_activation_items_parent on public.activation_items(parent_item_id);

-- Flat dependency graph: from_item_id depends on to_item_id. Edges are scoped to a
-- brand for cheap loading; uniqueness prevents duplicate edges.
create table public.activation_deps (
  id           bigint generated by default as identity primary key,
  brand_id     bigint not null references public.activation_brands(id) on delete cascade,
  from_item_id bigint not null references public.activation_items(id) on delete cascade,
  to_item_id   bigint not null references public.activation_items(id) on delete cascade,
  created_at   timestamptz not null default now(),
  unique (from_item_id, to_item_id)
);
create index idx_activation_deps_brand on public.activation_deps(brand_id);
create index idx_activation_deps_from on public.activation_deps(from_item_id);
create index idx_activation_deps_to on public.activation_deps(to_item_id);

-- ===== RLS: shared internal workspace (same model as deals/leads) =====
do $$
declare t text;
begin
  foreach t in array array[
    'activation_brands','activation_items','activation_deps'
  ] loop
    execute format('alter table public.%I enable row level security;', t);
    execute format(
      'create policy "authenticated full access" on public.%I for all to authenticated using (true) with check (true);',
      t
    );
  end loop;
end $$;

-- ===== Spawn function =====
-- Atomically create a brand + its five system lanes, default tasks, and template
-- dependency edges the first time a won deal is seen. Idempotent via the unique
-- deal_id (on conflict do nothing); a second caller short-circuits. This is the
-- single retune point for the system template (lane labels, deadline days, tasks,
-- intra-template deps). security invoker so workspace RLS applies to the caller.
create or replace function public.ensure_activation_brand(p_deal_id bigint)
returns bigint language plpgsql security invoker as $$
declare
  v_brand_id  bigint;
  v_committed date;
  -- lane ids
  l_tracking bigint; l_briefs bigint; l_assets bigint; l_creators bigint; l_live bigint;
  -- task ids that participate in template dependency edges
  t_postback bigint; t_test bigint;
  t_assetsin bigint; t_script bigint; t_approve bigint;
  t_source bigint; t_assign bigint;
  t_distribute bigint; t_posts bigint;
begin
  -- committed_date = first activation-stage entry, by insertion order (id), since
  -- stage_history.entered_at is user-editable. Fallback to today if (unexpectedly)
  -- no activation history exists yet.
  select sh.entered_at::date into v_committed
    from public.stage_history sh
   where sh.deal_id = p_deal_id
     and sh.stage in ('A1','A2','A3','A4','A5')
   order by sh.id asc
   limit 1;
  v_committed := coalesce(v_committed, current_date);

  insert into public.activation_brands (deal_id, committed_date)
  values (p_deal_id, v_committed)
  on conflict (deal_id) do nothing
  returning id into v_brand_id;

  -- Another caller already spawned this brand (or it pre-exists) — nothing to do.
  if v_brand_id is null then
    return null;
  end if;

  -- ----- Lanes (sort_order 0..4) -----
  insert into public.activation_items (brand_id, kind, label, is_system, hard_deadline_day, sort_order)
    values (v_brand_id, 'lane', 'Tracking & Integration', true, 5, 0) returning id into l_tracking;
  insert into public.activation_items (brand_id, kind, label, is_system, hard_deadline_day, sort_order)
    values (v_brand_id, 'lane', 'Briefs & Ad Scripts', true, 8, 1) returning id into l_briefs;
  insert into public.activation_items (brand_id, kind, label, is_system, hard_deadline_day, sort_order)
    values (v_brand_id, 'lane', 'Marketing Assets', true, 10, 2) returning id into l_assets;
  insert into public.activation_items (brand_id, kind, label, is_system, hard_deadline_day, sort_order)
    values (v_brand_id, 'lane', 'Creator Match', true, 12, 3) returning id into l_creators;
  insert into public.activation_items (brand_id, kind, label, is_system, is_live, hard_deadline_day, sort_order)
    values (v_brand_id, 'lane', 'Briefed & Live', true, true, null, 4) returning id into l_live;

  -- ----- Tracking & Integration tasks -----
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_tracking, 'Build Everflow offer', true, 0);
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_tracking, 'Wire postback to brand endpoint', true, 1) returning id into t_postback;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_tracking, 'Fire test conversion & verify', true, 2) returning id into t_test;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_tracking, 'Confirm payout caps with brand', true, 3);

  -- ----- Briefs & Ad Scripts tasks -----
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_briefs, 'Get marketing assets from brand', true, 0) returning id into t_assetsin;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_briefs, 'Write ad script', true, 1) returning id into t_script;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_briefs, 'Confirm coupon codes / offers', true, 2);
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_briefs, 'Brand approval on scripts', true, 3) returning id into t_approve;

  -- ----- Marketing Assets tasks -----
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_assets, 'Request brand guidelines', true, 0);
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_assets, 'Collect logos & creative', true, 1);
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_assets, 'Confirm usage rights', true, 2);

  -- ----- Creator Match tasks -----
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_creators, 'Source creators against vertical', true, 0) returning id into t_source;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_creators, 'Confirm availability', true, 1);
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_creators, 'Assign creators in dashboard', true, 2) returning id into t_assign;

  -- ----- Briefed & Live tasks -----
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_live, 'Distribute briefs + assets to creators', true, 0) returning id into t_distribute;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_live, 'Confirm content schedule', true, 1);
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_live, 'Verify first posts live', true, 2) returning id into t_posts;
  insert into public.activation_items (brand_id, kind, parent_item_id, label, is_system, sort_order)
    values (v_brand_id, 'task', l_live, 'Confirm tracking links in content', true, 3);

  -- ----- Dependency edges (from depends on to) -----
  insert into public.activation_deps (brand_id, from_item_id, to_item_id) values
    (v_brand_id, t_test, t_postback),      -- Fire test conversion needs postback
    (v_brand_id, t_script, t_assetsin),    -- Write ad script needs assets in
    (v_brand_id, t_approve, t_script),     -- Brand approval needs script
    (v_brand_id, t_assign, t_source),      -- Assign creators needs sourcing
    (v_brand_id, t_posts, t_distribute),   -- Verify first posts needs distribution
    -- Briefed & Live convergence: depends on Briefs + Assets + Creator Match (all done)
    (v_brand_id, l_live, l_briefs),
    (v_brand_id, l_live, l_assets),
    (v_brand_id, l_live, l_creators);

  return v_brand_id;
end;
$$;
grant execute on function public.ensure_activation_brand(bigint) to authenticated;

-- Pin search_path to empty (all refs above are schema-qualified) — matches 0004.
alter function public.ensure_activation_brand(bigint) set search_path = '';
