-- Stakeholders: a deal can have many named contacts (Champion, Economic Buyer,
-- Blocker, Influencer, Other), one of whom is flagged primary for board-card
-- display. Deal-scoped and free-form (name/email/linkedin copied in, not a
-- live FK to lead_contacts) — a stakeholder's role/primary-flag is a
-- deal-relationship concept that doesn't belong on a company-scoped contact
-- row, and a brand-new deal may have no company/lead link at all.
-- source_contact_id is an optional soft-pointer back to lead_contacts, kept
-- only for traceability when a stakeholder was seeded from the People
-- directory — it is never joined on for display.
create table public.deal_stakeholders (
  id                bigint generated by default as identity primary key,
  deal_id           bigint not null references public.deals(id) on delete cascade,
  name              text not null,
  role              text not null default 'Other',
  email             text,
  linkedin          text,
  is_primary        boolean not null default false,
  source_contact_id bigint references public.lead_contacts(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index idx_deal_stakeholders_deal on public.deal_stakeholders(deal_id);

-- Enforce "one primary per deal" at the DB level.
create unique index uq_deal_stakeholders_primary
  on public.deal_stakeholders(deal_id) where is_primary;

alter table public.deal_stakeholders enable row level security;
create policy "authenticated full access" on public.deal_stakeholders
  for all to authenticated using (true) with check (true);

-- Tag which stakeholder a touch was with. Nullable — existing touches (and
-- any future touch logged without a tag) have none.
alter table public.touch_log
  add column stakeholder_id bigint references public.deal_stakeholders(id) on delete set null;
create index idx_touch_log_stakeholder on public.touch_log(stakeholder_id);

-- Atomic "set primary": unset the current primary (if any) then set the new
-- one, in one statement-level transaction, so we never trip the partial
-- unique index above with a client-side unset-then-set round trip. Mirrors
-- start_outreach()'s existing atomic-RPC pattern from 0003.
create or replace function public.set_primary_stakeholder(p_deal_id bigint, p_stakeholder_id bigint)
returns void language plpgsql security invoker as $$
begin
  update public.deal_stakeholders set is_primary = false, updated_at = now()
   where deal_id = p_deal_id and is_primary = true;
  update public.deal_stakeholders set is_primary = true, updated_at = now()
   where id = p_stakeholder_id and deal_id = p_deal_id;
end;
$$;
grant execute on function public.set_primary_stakeholder(bigint, bigint) to authenticated;
