-- Tasks on a deal. status is only ever 'open' or 'done' — "overdue" is a
-- derived/display-only state (open + due_date in the past), computed
-- client-side, never stored, matching how days_in_stage/days_in_pipeline are
-- already handled for deals.
create table public.deal_tasks (
  id           bigint generated by default as identity primary key,
  deal_id      bigint not null references public.deals(id) on delete cascade,
  title        text not null,
  owner        text,
  due_date     date,
  status       text not null default 'open',
  stage_code   text,
  completed_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_deal_tasks_deal on public.deal_tasks(deal_id);

alter table public.deal_tasks enable row level security;
create policy "authenticated full access" on public.deal_tasks
  for all to authenticated using (true) with check (true);
