-- Rich-text notes on a deal. content_json stores the Tiptap document
-- (editor.getJSON()) rather than raw HTML: it's what Tiptap natively
-- reads/writes, avoids re-parsing/sanitizing HTML on every load, and
-- sidesteps XSS risk from rendering stored HTML directly. content_text is a
-- client-derived plain-text mirror (editor.getText()) so previews and the
-- activity timeline don't need to spin up a second Tiptap instance just to
-- extract a snippet.
create table public.deal_notes (
  id           bigint generated by default as identity primary key,
  deal_id      bigint not null references public.deals(id) on delete cascade,
  content_json jsonb not null,
  content_text text not null,
  author       text,
  pinned       boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_deal_notes_deal on public.deal_notes(deal_id);

alter table public.deal_notes enable row level security;
create policy "authenticated full access" on public.deal_notes
  for all to authenticated using (true) with check (true);
