-- File attachments on a deal. This is the first file-upload feature in the
-- app, so it introduces Supabase Storage from scratch: a private bucket
-- (this whole app is login-gated per 0002's own comment — storage should
-- match that, not be world-readable) with a 25MB size cap and a mime
-- allowlist enforced BY STORAGE ITSELF at upload time. There is no custom
-- backend in this app, but Storage is real server-side enforcement for this
-- one concern — client-side validation is a fast-fail UX nicety on top, not
-- the actual guardrail.
create table public.deal_attachments (
  id           bigint generated by default as identity primary key,
  deal_id      bigint not null references public.deals(id) on delete cascade,
  filename     text not null,
  storage_path text not null,
  file_size    bigint,
  content_type text,
  uploaded_by  text,
  created_at   timestamptz not null default now()
);
create index idx_deal_attachments_deal on public.deal_attachments(deal_id);

alter table public.deal_attachments enable row level security;
create policy "authenticated full access" on public.deal_attachments
  for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'deal-attachments', 'deal-attachments', false, 26214400,
  array[
    'image/png', 'image/jpeg', 'image/gif', 'image/webp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/plain', 'text/csv'
  ]
);

create policy "authenticated read deal-attachments" on storage.objects
  for select to authenticated using (bucket_id = 'deal-attachments');
create policy "authenticated write deal-attachments" on storage.objects
  for insert to authenticated with check (bucket_id = 'deal-attachments');
create policy "authenticated delete deal-attachments" on storage.objects
  for delete to authenticated using (bucket_id = 'deal-attachments');
