-- Stage exit criteria: an admin-configured list of checklist labels per
-- stage (stage_exit_criteria), and per-deal checked state against that list
-- (deal_stage_checklist). Advisory only for v1 — checking every criterion
-- never blocks a manual stage move.
--
-- No reset-on-stage-change trigger is needed: reads are always scoped to the
-- deal's CURRENT stage's criteria (a join, not a stored snapshot), so moving
-- to a new stage naturally shows fresh unchecked criteria for free. Rows for
-- a deal's prior stage just sit there afterward, harmlessly, as history.
create table public.stage_exit_criteria (
  id         bigint generated by default as identity primary key,
  stage_code text not null,
  label      text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_stage_exit_criteria_stage on public.stage_exit_criteria(stage_code);

create table public.deal_stage_checklist (
  id           bigint generated by default as identity primary key,
  deal_id      bigint not null references public.deals(id) on delete cascade,
  criterion_id bigint not null references public.stage_exit_criteria(id) on delete cascade,
  checked      boolean not null default false,
  updated_at   timestamptz not null default now(),
  unique (deal_id, criterion_id)
);
create index idx_deal_stage_checklist_deal on public.deal_stage_checklist(deal_id);

alter table public.stage_exit_criteria enable row level security;
create policy "authenticated full access" on public.stage_exit_criteria
  for all to authenticated using (true) with check (true);
alter table public.deal_stage_checklist enable row level security;
create policy "authenticated full access" on public.deal_stage_checklist
  for all to authenticated using (true) with check (true);
