-- Manual deal-to-deal relations. Stored symmetrically: linking A<->B writes
-- both (A,B) and (B,A) rows, and unlinking deletes both. This keeps every
-- read a plain single-predicate `where deal_id = X` query, matching this
-- codebase's existing preference for simple queries over OR clauses (see
-- listContacts/getCompanyActivity in api.js) — doubling a handful of tiny
-- junction rows per deal is free.
create table public.deal_relations (
  id              bigint generated by default as identity primary key,
  deal_id         bigint not null references public.deals(id) on delete cascade,
  related_deal_id bigint not null references public.deals(id) on delete cascade,
  created_at      timestamptz not null default now(),
  constraint chk_deal_relations_not_self check (deal_id <> related_deal_id),
  unique (deal_id, related_deal_id)
);
create index idx_deal_relations_deal on public.deal_relations(deal_id);
create index idx_deal_relations_related on public.deal_relations(related_deal_id);

alter table public.deal_relations enable row level security;
create policy "authenticated full access" on public.deal_relations
  for all to authenticated using (true) with check (true);
