-- Ad Tracker: per-client creator-ad pipeline (submitted -> sent to brand ->
-- brand approved -> live, or rejected). Mirrors the deals/stage_history
-- pattern (0001/0003) rather than the generic lanes/tasks/deps engine that
-- was tried in 0014 and ripped out in 0018 as unshipped/orphaned — keep this
-- one small and purpose-built.

create table public.ad_items (
  id             bigint generated by default as identity primary key,
  lead_id        bigint not null references public.leads(id) on delete cascade,
  creator_name   text not null,
  creator_handle text,
  platform       text,        -- client-validated only, e.g. TikTok/Instagram/YouTube/Other
  creator_owner  text,        -- OWNERS value (creator-team person)
  brand_owner    text,        -- OWNERS value (brand-team person)
  notes          text,
  current_stage  text not null default 'submitted',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index idx_ad_items_lead on public.ad_items(lead_id);

-- Append-only stage log, one row per stage entry (same shape as stage_history).
create table public.ad_item_stage_history (
  id         bigint generated by default as identity primary key,
  ad_item_id bigint not null references public.ad_items(id) on delete cascade,
  stage      text not null,
  entered_at timestamptz not null default now()
);
create index idx_ad_item_stage_history_item on public.ad_item_stage_history(ad_item_id);

alter table public.ad_items enable row level security;
create policy "authenticated full access" on public.ad_items
  for all to authenticated using (true) with check (true);

alter table public.ad_item_stage_history enable row level security;
create policy "authenticated full access" on public.ad_item_stage_history
  for all to authenticated using (true) with check (true);

-- Keep ad_items.current_stage / updated_at in sync on each stage_history
-- insert, exactly like sync_deal_current_stage() in 0003.
create or replace function public.sync_ad_item_current_stage()
returns trigger language plpgsql as $$
begin
  update public.ad_items
     set current_stage = new.stage, updated_at = new.entered_at
   where id = new.ad_item_id;
  return new;
end;
$$;
create trigger trg_ad_item_stage_history_sync
  after insert on public.ad_item_stage_history
  for each row execute function public.sync_ad_item_current_stage();

-- Pin search_path at creation time (see 0004) — all refs above are
-- schema-qualified.
alter function public.sync_ad_item_current_stage() set search_path = '';

-- ad_item_summaries: ad_items + entered_at of the current stage (for "days in
-- stage") + the timestamp the item first hit 'brand_approved' (SLA clock
-- start), so the client can compute the 14-day SLA countdown without pulling
-- full history. Mirrors deal_summaries (0003/0016/0017/0027).
create view public.ad_item_summaries with (security_invoker = true) as
select ai.*,
  (select sh.entered_at
     from public.ad_item_stage_history sh
    where sh.ad_item_id = ai.id and sh.stage = ai.current_stage
    order by sh.entered_at desc, sh.id desc
    limit 1) as current_stage_entered_at,
  (select sh.entered_at
     from public.ad_item_stage_history sh
    where sh.ad_item_id = ai.id and sh.stage = 'brand_approved'
    order by sh.entered_at asc, sh.id asc
    limit 1) as approved_at
from public.ad_items ai;
