-- Client Spend & Goals: track monthly revenue billed to a client (Everflow,
-- payout + margin) against a monthly goal Panel sets. Mirrors the Apollo
-- enrichment pattern — an edge function does the external API call and
-- writes back via the service role; actuals are cached, not queried live
-- (see supabase/functions/everflow-sync for why: completed months don't
-- change, and Everflow reporting calls are too slow/rate-limited to run on
-- every profile view across many historical months).

alter table public.leads
  add column if not exists everflow_advertiser_id text;

create table public.client_spend_goals (
  id           bigint generated by default as identity primary key,
  lead_id      bigint not null references public.leads(id) on delete cascade,
  month        date not null,       -- always the 1st of the month, e.g. 2026-07-01
  goal_amount  integer not null,    -- whole USD dollars, matches deals.pilot_spend convention
  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint chk_client_spend_goals_month_first check (month = date_trunc('month', month)::date),
  unique (lead_id, month)
);
create index idx_client_spend_goals_lead on public.client_spend_goals(lead_id);

create table public.client_spend_actuals (
  id           bigint generated by default as identity primary key,
  lead_id      bigint not null references public.leads(id) on delete cascade,
  month        date not null,
  revenue      integer,             -- billed to advertiser (payout + margin) — the tracked "spend"
  payout       integer,             -- paid to affiliates/creators, kept for future margin display
  synced_at    timestamptz not null default now(),
  everflow_raw jsonb,                -- raw reporting-API row, mirrors apollo_raw
  constraint chk_client_spend_actuals_month_first check (month = date_trunc('month', month)::date),
  unique (lead_id, month)
);
create index idx_client_spend_actuals_lead on public.client_spend_actuals(lead_id);

alter table public.client_spend_goals enable row level security;
create policy "authenticated full access" on public.client_spend_goals
  for all to authenticated using (true) with check (true);

alter table public.client_spend_actuals enable row level security;
create policy "authenticated full access" on public.client_spend_actuals
  for all to authenticated using (true) with check (true);
