-- Per-client "quality" event tracking: a secondary Everflow conversion event
-- (distinct from the primary billable event) that represents a real business
-- outcome rather than just volume — e.g. Current's primary event is
-- downloads, but "Payroll" (someone switching payroll direct deposit) is the
-- quality signal. The event name is free text per client since different
-- clients define quality differently; see supabase/functions/_shared/everflow.ts
-- for how it's queried (Everflow's entity/table report, advertiser_event_name
-- column, confirmed via a live test call against Current's real advertiser id).

alter table public.leads
  add column if not exists everflow_quality_event_name text;

create table public.client_quality_actuals (
  id            bigint generated by default as identity primary key,
  lead_id       bigint not null references public.leads(id) on delete cascade,
  month         date not null,
  event_name    text not null, -- snapshot of leads.everflow_quality_event_name at sync time
  event_count   integer,
  event_revenue integer, -- nullable: not every event type carries revenue
  synced_at     timestamptz not null default now(),
  everflow_raw  jsonb,
  constraint chk_client_quality_actuals_month_first check (month = date_trunc('month', month)::date),
  unique (lead_id, month, event_name)
);
create index idx_client_quality_actuals_lead on public.client_quality_actuals(lead_id);

alter table public.client_quality_actuals enable row level security;
create policy "authenticated full access" on public.client_quality_actuals
  for all to authenticated using (true) with check (true);

-- merge_leads: carry over both Everflow fields (everflow_advertiser_id was a
-- pre-existing gap — never filled on merge — and the new
-- everflow_quality_event_name would inherit the same gap if not added now),
-- plus reassign client_quality_actuals rows the same way client_spend_actuals
-- already is.
create or replace function public.merge_leads(
  p_winner_id bigint,
  p_loser_id  bigint
) returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_winner        public.leads%rowtype;
  v_loser         public.leads%rowtype;
  v_now           timestamptz := now();
begin
  if p_winner_id = p_loser_id then
    raise exception 'Cannot merge a company into itself';
  end if;

  select * into v_winner from public.leads where id = p_winner_id;
  if not found then
    raise exception 'Winner lead % not found', p_winner_id;
  end if;
  select * into v_loser from public.leads where id = p_loser_id;
  if not found then
    raise exception 'Loser lead % not found', p_loser_id;
  end if;

  -- Deal reconciliation: leads.deal_id has no FK, so nothing else protects it.
  if v_loser.deal_id is not null then
    if v_winner.deal_id is not null then
      raise exception
        'Both companies have an active deal (winner deal %, loser deal %) — move or close one deal before merging',
        v_winner.deal_id, v_loser.deal_id;
    end if;
    update public.leads
       set deal_id = v_loser.deal_id, in_pipeline = v_loser.in_pipeline
     where id = p_winner_id;
  end if;

  -- Reassign simple children (no uniqueness to worry about).
  update public.lead_contacts set lead_id = p_winner_id where lead_id = p_loser_id;
  update public.ad_items      set lead_id = p_winner_id where lead_id = p_loser_id;

  -- Reassign lead_signals, keeping the winner's value on a signal_key clash.
  insert into public.lead_signals (lead_id, signal_key, value, notes, updated_at)
  select p_winner_id, signal_key, value, notes, updated_at
    from public.lead_signals
   where lead_id = p_loser_id
  on conflict (lead_id, signal_key) do nothing;

  -- Reassign spend goals/actuals, keeping the winner's row on a month clash.
  insert into public.client_spend_goals (lead_id, month, goal_amount, notes, created_at, updated_at)
  select p_winner_id, month, goal_amount, notes, created_at, updated_at
    from public.client_spend_goals
   where lead_id = p_loser_id
  on conflict (lead_id, month) do nothing;

  insert into public.client_spend_actuals (lead_id, month, revenue, payout, synced_at, everflow_raw)
  select p_winner_id, month, revenue, payout, synced_at, everflow_raw
    from public.client_spend_actuals
   where lead_id = p_loser_id
  on conflict (lead_id, month) do nothing;

  -- Reassign quality actuals, keeping the winner's row on a (month, event_name) clash.
  insert into public.client_quality_actuals (lead_id, month, event_name, event_count, event_revenue, synced_at, everflow_raw)
  select p_winner_id, month, event_name, event_count, event_revenue, synced_at, everflow_raw
    from public.client_quality_actuals
   where lead_id = p_loser_id
  on conflict (lead_id, month, event_name) do nothing;

  -- Repoint the review queue so it doesn't point at a row about to disappear.
  update public.company_suggestions
     set matched_lead_id = p_winner_id
   where matched_lead_id = p_loser_id;

  -- Fill blanks on the winner from the loser; never overwrite a real value.
  update public.leads
     set website                     = coalesce(nullif(btrim(v_winner.website), ''), v_loser.website),
         domain                      = coalesce(nullif(btrim(v_winner.domain), ''), v_loser.domain),
         hq_location                 = coalesce(nullif(btrim(v_winner.hq_location), ''), v_loser.hq_location),
         headcount                   = coalesce(nullif(btrim(v_winner.headcount), ''), v_loser.headcount),
         description                 = coalesce(nullif(btrim(v_winner.description), ''), v_loser.description),
         industry                    = coalesce(nullif(btrim(v_winner.industry), ''), v_loser.industry),
         estimated_revenue           = coalesce(v_winner.estimated_revenue, v_loser.estimated_revenue),
         founded_year                = coalesce(v_winner.founded_year, v_loser.founded_year),
         apollo_org_id               = coalesce(nullif(btrim(v_winner.apollo_org_id), ''), v_loser.apollo_org_id),
         everflow_advertiser_id      = coalesce(nullif(btrim(v_winner.everflow_advertiser_id), ''), v_loser.everflow_advertiser_id),
         everflow_quality_event_name = coalesce(nullif(btrim(v_winner.everflow_quality_event_name), ''), v_loser.everflow_quality_event_name),
         is_client                   = v_winner.is_client or v_loser.is_client,
         updated_at                  = v_now
   where id = p_winner_id;

  -- Everything still on the loser at this point (lead_signals/spend rows that
  -- clashed and were skipped above, plus the row itself) goes via cascade.
  delete from public.leads where id = p_loser_id;
end;
$$;
