-- Per-offer Everflow tracking: some advertisers run several simultaneous
-- offers under one account (e.g. tiered payouts T1/T2/T3/T4 for the same
-- property) — client_spend_actuals only ever tracked one aggregate number
-- per advertiser, so tier-level performance was invisible. Offers are
-- auto-discovered from Everflow's own per-offer report breakdown (see
-- supabase/functions/_shared/everflow.ts's fetchAdvertiserOfferBreakdown) —
-- there's no new id for a rep to type in; everflow-sync upserts a
-- client_offers row per offer id it finds under the client's existing
-- everflow_advertiser_id, and display_name is the rep's own optional rename
-- (e.g. "T1") layered over Everflow's own offer label.

create table public.client_offers (
  id                  bigint generated by default as identity primary key,
  lead_id             bigint not null references public.leads(id) on delete cascade,
  everflow_offer_id   text not null,
  everflow_offer_name text,
  display_name        text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (lead_id, everflow_offer_id)
);
create index idx_client_offers_lead on public.client_offers(lead_id);

create table public.client_offer_spend_actuals (
  id           bigint generated by default as identity primary key,
  offer_id     bigint not null references public.client_offers(id) on delete cascade,
  month        date not null,
  revenue      integer,
  payout       integer,
  synced_at    timestamptz not null default now(),
  everflow_raw jsonb,
  constraint chk_client_offer_spend_actuals_month_first check (month = date_trunc('month', month)::date),
  unique (offer_id, month)
);
create index idx_client_offer_spend_actuals_offer on public.client_offer_spend_actuals(offer_id);

alter table public.client_offers enable row level security;
create policy "authenticated full access" on public.client_offers
  for all to authenticated using (true) with check (true);

alter table public.client_offer_spend_actuals enable row level security;
create policy "authenticated full access" on public.client_offer_spend_actuals
  for all to authenticated using (true) with check (true);

-- merge_leads: reassign client_offers rows the same way client_spend_actuals
-- already is. On an everflow_offer_id clash (rare — would mean both
-- companies somehow synced the same Everflow offer id), keep the winner's
-- row and its display_name rather than overwrite a rep's rename; the
-- offer's own spend actuals still cascade-delete with the loser's row in
-- that clash case, same as any other on-conflict-do-nothing merge skip here.
create or replace function public.merge_leads(
  p_winner_id bigint,
  p_loser_id  bigint
) returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_winner        public.leads%rowtype;
  v_loser         public.leads%rowtype;
  v_now           timestamptz := now();
begin
  if p_winner_id = p_loser_id then
    raise exception 'Cannot merge a company into itself';
  end if;

  select * into v_winner from public.leads where id = p_winner_id;
  if not found then
    raise exception 'Winner lead % not found', p_winner_id;
  end if;
  select * into v_loser from public.leads where id = p_loser_id;
  if not found then
    raise exception 'Loser lead % not found', p_loser_id;
  end if;

  -- Deal reconciliation: leads.deal_id has no FK, so nothing else protects it.
  if v_loser.deal_id is not null then
    if v_winner.deal_id is not null then
      raise exception
        'Both companies have an active deal (winner deal %, loser deal %) — move or close one deal before merging',
        v_winner.deal_id, v_loser.deal_id;
    end if;
    update public.leads
       set deal_id = v_loser.deal_id, in_pipeline = v_loser.in_pipeline
     where id = p_winner_id;
  end if;

  -- Reassign simple children (no uniqueness to worry about).
  update public.lead_contacts set lead_id = p_winner_id where lead_id = p_loser_id;
  update public.ad_items      set lead_id = p_winner_id where lead_id = p_loser_id;

  -- Reassign lead_signals, keeping the winner's value on a signal_key clash.
  insert into public.lead_signals (lead_id, signal_key, value, notes, updated_at)
  select p_winner_id, signal_key, value, notes, updated_at
    from public.lead_signals
   where lead_id = p_loser_id
  on conflict (lead_id, signal_key) do nothing;

  -- Reassign spend goals/actuals, keeping the winner's row on a month clash.
  insert into public.client_spend_goals (lead_id, month, goal_amount, notes, created_at, updated_at)
  select p_winner_id, month, goal_amount, notes, created_at, updated_at
    from public.client_spend_goals
   where lead_id = p_loser_id
  on conflict (lead_id, month) do nothing;

  insert into public.client_spend_actuals (lead_id, month, revenue, payout, synced_at, everflow_raw)
  select p_winner_id, month, revenue, payout, synced_at, everflow_raw
    from public.client_spend_actuals
   where lead_id = p_loser_id
  on conflict (lead_id, month) do nothing;

  -- Reassign quality actuals, keeping the winner's row on a (month, event_name) clash.
  insert into public.client_quality_actuals (lead_id, month, event_name, event_count, event_revenue, synced_at, everflow_raw)
  select p_winner_id, month, event_name, event_count, event_revenue, synced_at, everflow_raw
    from public.client_quality_actuals
   where lead_id = p_loser_id
  on conflict (lead_id, month, event_name) do nothing;

  -- Reassign offers, keeping the winner's row (and its rep-set display_name)
  -- on an everflow_offer_id clash; the loser's row (and its cascading spend
  -- actuals) is simply left behind to be deleted with the loser below.
  update public.client_offers co
     set lead_id = p_winner_id
   where co.lead_id = p_loser_id
     and not exists (
       select 1 from public.client_offers w
        where w.lead_id = p_winner_id and w.everflow_offer_id = co.everflow_offer_id
     );

  -- Repoint the review queue so it doesn't point at a row about to disappear.
  update public.company_suggestions
     set matched_lead_id = p_winner_id
   where matched_lead_id = p_loser_id;

  -- Fill blanks on the winner from the loser; never overwrite a real value.
  update public.leads
     set website                     = coalesce(nullif(btrim(v_winner.website), ''), v_loser.website),
         domain                      = coalesce(nullif(btrim(v_winner.domain), ''), v_loser.domain),
         hq_location                 = coalesce(nullif(btrim(v_winner.hq_location), ''), v_loser.hq_location),
         headcount                   = coalesce(nullif(btrim(v_winner.headcount), ''), v_loser.headcount),
         description                 = coalesce(nullif(btrim(v_winner.description), ''), v_loser.description),
         industry                    = coalesce(nullif(btrim(v_winner.industry), ''), v_loser.industry),
         estimated_revenue           = coalesce(v_winner.estimated_revenue, v_loser.estimated_revenue),
         founded_year                = coalesce(v_winner.founded_year, v_loser.founded_year),
         apollo_org_id               = coalesce(nullif(btrim(v_winner.apollo_org_id), ''), v_loser.apollo_org_id),
         everflow_advertiser_id      = coalesce(nullif(btrim(v_winner.everflow_advertiser_id), ''), v_loser.everflow_advertiser_id),
         everflow_quality_event_name = coalesce(nullif(btrim(v_winner.everflow_quality_event_name), ''), v_loser.everflow_quality_event_name),
         is_client                   = v_winner.is_client or v_loser.is_client,
         updated_at                  = v_now
   where id = p_winner_id;

  -- Everything still on the loser at this point (lead_signals/spend rows that
  -- clashed and were skipped above, plus the row itself) goes via cascade.
  delete from public.leads where id = p_loser_id;
end;
$$;
