-- Structured data pulled out of each uploaded meeting transcript (the
-- deal_attachments rows tagged kind = 'transcript', see 0042), so the Calls
-- view can show every call as one row: who was on it, how long, what the brand
-- pushed on, where they bought in, the payout/cap they named, and the action
-- items. One row per transcript. The analyze-transcript Edge Function fills it
-- in (service role); re-analyzing overwrites the same row.
create table public.call_insights (
  id              bigint generated by default as identity primary key,
  attachment_id   bigint not null unique references public.deal_attachments(id) on delete cascade,
  deal_id         bigint not null references public.deals(id) on delete cascade,
  status          text not null default 'pending',   -- pending | done | error
  error           text,
  call_date       date,
  brand_side      text,                              -- "Name, title; Name"
  panel_side      text,                              -- "Raven, Tom"
  minutes         integer,
  questions_count integer,                           -- distinct questions the brand asked
  result          text,                              -- yes | follow_up | no | unclear
  outcome         text,                              -- one line: what the call ended on
  summary         text,
  next_step       text,
  action_items    jsonb not null default '[]',       -- [{ owner, task, due }]
  objections      jsonb not null default '[]',       -- [text] one line per objection / hard question
  buy_in_quote    text,
  buy_in_at       text,                              -- "27:11" timestamp in the call, if stated
  buy_in_before   text,                              -- what came right before the buy-in
  payout          text,                              -- CPA / payout discussed, e.g. "$35 on account creation"
  budget_cap      text,
  payable_event   text,                              -- signup, deposit, install…
  requested_at    timestamptz,                       -- last time analysis was started (spots a stalled run)
  analyzed_at     timestamptz,
  created_at      timestamptz not null default now()
);
create index idx_call_insights_deal on public.call_insights(deal_id);

-- Same workspace-wide access as deal_attachments (0023): every signed-in team
-- member sees every call.
alter table public.call_insights enable row level security;
create policy "authenticated full access" on public.call_insights
  for all to authenticated using (true) with check (true);
