-- The sales playbook, built into the app: deal economics (eCPM zone, bid
-- range, reverse-engineered payout), the pre-call qualifier, Meta Ad Library
-- checks, buyer tiers on contacts, call-cadence coaching, the post-signing
-- program lifecycle, and the playbook's own wording (objection answers,
-- cadence lines) — the last one seeded privately, never in this public repo.
-- Every table here is workspace-wide like the rest of the CRM (0002).

-- ===== A. Deal economics: the numbers behind one deal's offer =====
create table public.deal_economics (
  deal_id        bigint primary key references public.deals(id) on delete cascade,
  payable_event  text,          -- what the brand pays on: signup, install, first deposit…
  cpa            numeric,       -- $ per payable event (the brand's bid)
  brand_cac      numeric,       -- the brand's current CAC: the ceiling on a profitable bid
  conv_per_1k    numeric,       -- expected payable events per 1,000 views
  user_value     numeric,       -- what a fully converted user is worth to the brand
  reach_rate     numeric,       -- % of payable-event users who reach that valuable step
  notes          text,
  updated_at     timestamptz not null default now()
);

-- ===== B. Qualifier inputs. Blank fields fall back to Apollo's data. =====
create table public.lead_qualifier (
  lead_id        bigint primary key references public.leads(id) on delete cascade,
  funding_stage  text,          -- bootstrapped | seed | seriesa | seriesb | seriesc | late | public
  funding_date   date,          -- date of the latest round
  employees      text,          -- micro | small | mid | large | enterprise
  vertical_key   text,          -- neobank | bnpl | investing | credit | cashadvance | insurance |
                                -- lending | sportsbook | prediction | legal | other
  ad_spend       text,          -- low | mid | high | whale (monthly paid media)
  updated_at     timestamptz not null default now()
);

-- ===== D. Meta Ad Library checks: who the brand pays right now, and how =====
create table public.ad_library_checks (
  id               bigint generated by default as identity primary key,
  lead_id          bigint not null references public.leads(id) on delete cascade,
  checked_on       date not null default current_date,
  active_ads       integer,               -- partnered ads live when checked
  creators         jsonb not null default '[]', -- [{ handle, angle }]
  hook             text,                  -- the outreach hook this suggests
  notes            text,
  checked_by       text,                  -- OWNERS value
  created_at       timestamptz not null default now()
);
create index idx_ad_library_checks_lead on public.ad_library_checks(lead_id, checked_on desc);

-- ===== C. Buyer tier override (null = derived from the job title) =====
alter table public.lead_contacts
  add column if not exists buyer_tier text; -- primary | decision | champion | skip

-- ===== E. Call coaching: which cadence steps the call hit =====
-- { step_key: { hit: true|false, note: "…" } }, steps listed in lib/cadence.js
alter table public.call_insights
  add column if not exists cadence jsonb not null default '{}';

-- ===== G. Client program inputs Everflow can't provide =====
create table public.client_programs (
  lead_id          bigint primary key references public.leads(id) on delete cascade,
  tracking_live    boolean,      -- postback / integration confirmed working
  active_creators  integer,      -- override; otherwise counted from live ad items
  monthly_views    bigint,       -- last month's views across the program (for CTR / eCPM)
  notes            text,
  updated_at       timestamptz not null default now()
);

-- ===== E/F. The playbook's wording, kept out of the public code =====
-- kind: 'objection' (key = pushback theme), 'cadence' (key = cadence step),
--       'qualifier' (key = hyper | efficient | unclear | early)
create table public.playbook_entries (
  id         bigint generated by default as identity primary key,
  kind       text not null,
  key        text not null,
  title      text,
  body       text,              -- the approach, in the playbook's words
  say        text,              -- a line to say on the call
  sort       integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (kind, key)
);

alter table public.deal_economics    enable row level security;
alter table public.lead_qualifier    enable row level security;
alter table public.ad_library_checks enable row level security;
alter table public.client_programs   enable row level security;
alter table public.playbook_entries  enable row level security;
create policy "authenticated full access" on public.deal_economics
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.lead_qualifier
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.ad_library_checks
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.client_programs
  for all to authenticated using (true) with check (true);
create policy "authenticated full access" on public.playbook_entries
  for all to authenticated using (true) with check (true);
